export const readingLessons = [
  { title: '1. Establish the question before the interpretation', text: 'Ask what the person wants to understand and whether they want a symbolic reading. Begin with an open question such as “What part of your life are you reflecting on?” A birthday supplies arithmetic, not access to someone’s private history. Let their own description set the context. When practicing, write the question down before examining the numbers so that you can notice whether you later reshape it to fit the result.', exercise: 'Practice opening a session in two sentences: explain the symbolic method, then ask one neutral question. Leave room for the person to decline or correct your framing.' },
  { title: '2. Check the arithmetic and name the convention', text: 'Asteria reduces the birth month, day and year separately, preserving 11, 22 and 33, then reduces their sum with the same rule. The birthday talent is the reduced day alone. Personal year uses birth month, birth day and the selected calendar year, fully reducing to 1–9. Other schools may sum every digit at once, retain the unreduced birthday or use birthday-to-birthday timing. Different results can reflect a different convention rather than an arithmetic error.', exercise: 'Calculate July 17, 1990: month 7, day 17 → 8, year 1990 → 19 → 10 → 1; 7 + 8 + 1 = 16 → 7. In 2026, personal year is 7 + 8 + 1 = 16 → 7. Explain why the repeated 7 has two different roles.' },
  { title: '3. Read the role before reading the number', text: 'Life path is a broad theme for the reading. Birthday is a more specific talent or style of contribution. Personal year is a changing symbolic focus. A Four life path and Four birthday should not receive identical paragraphs: one asks about a recurring relationship with structure, while the other asks how practical follow-through may be a useful skill. Keep each role distinct before combining them. Name-based Expression, Soul Urge and Personality numbers require a name and are not inferred from a birth date here.', exercise: 'Describe Four once as a life theme and once as a birthday talent without repeating the same sentence. Then explain how a personal year of Five might invite a flexible experiment within that structure.' },
  { title: '4. Treat repetition and contrast as questions', text: 'When numbers repeat, a theme appears in more than one position. That is a reason to ask how the roles differ, not a mathematical measure of personality intensity. When themes contrast, explore how they cooperate: a structured life-path theme might be supported by an expressive birthday talent. Do not manufacture conflict because two labels sound different. Ask for examples that fit and examples that do not, and let the person’s answers revise your interpretation.', exercise: 'Choose two different numbers from the reference. Write one possible way they could support each other and one question you would ask before deciding that there is any tension.' },
  { title: '5. Make the reading testable through examples', text: 'Broad language can sound personal even when it applies to many people. Avoid turning agreement into proof of prediction. Ask for a specific example, note counterexamples and distinguish observation from interpretation. Instead of “You always carry everyone,” try “Does responsibility feel balanced in your current situation?” A useful reader listens to the answer rather than steering the person toward the expected story.', exercise: 'Take a confident-sounding claim and rewrite it as an open question. Write down what answer would lead you to change the reading, rather than treating every response as confirmation.' },
  { title: '6. Close with agency and a practical next step', text: 'Summarize the themes in the person’s own language and ask what, if anything, was useful. Offer one small, optional action connected to their stated question. Do not announce inevitable loss, illness, pregnancy, wealth or a fixed relationship outcome. A symbolic practice cannot establish these events. Explain the limits of the method, keep personal information private and avoid creating a need for repeated readings to make ordinary decisions.', exercise: 'Close a practice reading with a summary, a question and one reversible action. Ask the person to identify what did not fit as well as what did, then revise your notes.' },
];

